use_constraints: false
real_world: false
num_reps: 5
cylinders:
  -
    name: pole
    frame: /base_link
    position: [ 0.62, -0.62, 0.6 ]
    orientation: [ 0.0, 0.0, 0.0 ]
    dimensions: [ 0.1, 1.2 ]

# poses are in x, y, z, roll, pitch, yaw format
poses_frame: /torso_lift_link
poses:
  - [ 0.76, -0.19, 0.0, 0.0, 0.0, 0.0 ]
  - [ 0.35, -0.85, 0.0, 0.0, 0.0, -1.0 ]
