collision_clearance: 0.07

collision_links:
  r_gripper_l_finger_link:
    link_radius: 0.03
    link_extension: 0.01
  r_gripper_r_finger_link:
    link_radius: 0.03
    link_extension: 0.01
  r_gripper_l_finger_tip_link:
    link_radius: 0.03
    link_extension: 0.01
  r_gripper_r_finger_tip_link:
    link_radius: 0.03
    link_extension: 0.01
  r_gripper_palm_link:
    link_radius: 0.06
  r_forearm_link:
    link_radius: 0.065
  r_upper_arm_link:
    link_radius: 0.10
  l_gripper_l_finger_link:
    link_radius: 0.03
    link_extension: 0.01
  l_gripper_r_finger_link:
    link_radius: 0.03
    link_extension: 0.01
  l_gripper_l_finger_tip_link:
    link_radius: 0.03
    link_extension: 0.01
  l_gripper_r_finger_tip_link:
    link_radius: 0.03
    link_extension: 0.01
  l_gripper_palm_link:
    link_radius: 0.06
  l_forearm_link:
    link_radius: 0.065
  l_upper_arm_link:
    link_radius: 0.10

joint_costs:
  r_shoulder_pan_joint: 1.0
  r_shoulder_lift_joint: 1.0
  r_upper_arm_roll_joint: 1.0
  r_elbow_flex_joint: 1.0
  r_forearm_roll_joint: 1.0
  r_wrist_flex_joint: 1.0
  r_wrist_roll_joint: 1.0
  l_shoulder_pan_joint: 1.0
  l_shoulder_lift_joint: 1.0
  l_upper_arm_roll_joint: 1.0
  l_elbow_flex_joint: 1.0
  l_forearm_roll_joint: 1.0
  l_wrist_flex_joint: 1.0
  l_wrist_roll_joint: 1.0

joint_velocity_limits:
  r_shoulder_pan_joint: 0.5
  r_shoulder_lift_joint: 0.5
  r_upper_arm_roll_joint: 0.7
  r_elbow_flex_joint: 0.8
  r_forearm_roll_joint: 1.0
  r_wrist_flex_joint: 1.0
  r_wrist_roll_joint: 1.0
  l_shoulder_pan_joint: 0.5
  l_shoulder_lift_joint: 0.5
  l_upper_arm_roll_joint: 0.7
  l_elbow_flex_joint: 0.8
  l_forearm_roll_joint: 1.0
  l_wrist_flex_joint: 1.0
  l_wrist_roll_joint: 1.0


reference_frame: base_link

collision_space:
  size_x: 2.0
  size_y: 3.0
  size_z: 2.2
  origin_x: -0.5
  origin_y: -1.5
  origin_z: -0.3
  resolution: 0.015
  field_bias_x: 0.0
  field_bias_y: 0.0
  field_bias_z: 0.0
      
stomp_collision_operations:
  - object1: left_arm
    object2: left_arm
    operation: disable

  - object1: right_arm
    object2: right_arm
    operation: disable

  - object1: left_arm
    object2: l_end_effector
    operation: disable
  
  - object1: right_arm
    object2: r_end_effector
    operation: disable

  - object1: right_arm
    object2: torso_lift_link
    operation: disable

  - object1: left_arm
    object2: torso_lift_link
    operation: disable
