blobs: red blue purple cyan brown

red:
  offset: 0.025
  r: 255
  g: 0
  b: 0

blue:
  offset: 0.045
  r: 0
  g: 0
  b: 255

purple:
  offset: 0.04
  r: 255
  g: 0
  b: 255

cyan:
  offset: 0.04
  r: 0
  g: 220
  b: 255

brown:
  offset: 0.04
  r: 153
  g: 102
  b: 51
      
filter_blob_position:
  name: filter_blob_position
  type: MultiChannelMeanFilterFloat
  params:
    number_of_observations: 4

filter_blob_velocity:
  name: filter_blob_velocity
  type: TransferFunctionFilter<float>
  params:
    a: [1.0, 0.9]
    b: [0.1]